name = "Subsystems"
uuid = "ba784b39-0cbe-4888-b1b2-848197028d33"
authors = ["Angelo Barboni <angelobarboni.eng@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
